homework_2
MaksKos/Homework_C_2 pull request #1
Opened 2021-11-09 10:48 UTC by MaksKos

Вариант #44
Вы разрабатываете специализированную БД сотрудников для корпорации, в которой работает порядка 10к человек. По ряду причин все данные необходимо хранить в оперативной памяти. Предложите такую эффективную упаковку данных о сотруднике (его имени, фамилии, поле, возрасте, заработной плате, должности и стаже работы). С её помощью реализуйте наивный последовательный алгоритм, который позволит быстро осуществлять поиск по запросу: самые возрастные и молодые сотрудники в каждой должности с сортировкой по фамилии, а затем – распараллельте его на несколько потоков.

2021-11-09 13:20 UTC, poofik33 commented
Надо было по-моему сделать все в прошлой репе в новой ветке

2021-11-09 17:22 UTC, poofik33 requested changes
1.(!) Нет паралллельной;
2. Нет запуска тестов под санитайзерами address, memory, thread;
3. Нет анализаторов и форматтеров cpplint, cppcheck, build-scanner, fbinfer, clang-tidy, clang-formatter
4. Рабочая ссылка на codecov https://app.codecov.io/gh/MaksKos/Homework_C_2/

2021-11-09 17:29 UTC, MaksKos commented
я может не совсем понял, но под санитайзерами имеется ввиду -fsanitaize=adress и для memory с thread те же параметры компиляции ? Просто с такими параметрами (они были в CMakeLists) не работает valgrind

2021-11-09 22:10 UTC, poofik33 commented
> я может не совсем понял, но под санитайзерами имеется ввиду -fsanitaize=adress и для memory с thread те же параметры компиляции ? Просто с такими параметрами (они были в CMakeLists) не работает valgrind
Либо валгринд, либо санитайзеры - запускается что-то одно

2022-01-08 14:47 UTC, leshiy1295 reviewed
Очень слабая работа, к сожалению.
Код очень тяжело читаем, всё перемешано. Рекомендую уже "для себя" разнести всё аккуратно по модулям, чтобы каждая функция отвечала за одну небольшую зону ответственности

2022-01-08 14:47 UTC, leshiy1295 commented on .github/workflows/actions.yml
> +          flags: unittests
что-то низкое покрытие - порядка 40%
utils - вообще не покрывался (но это ясно, почему - т.к. Вы захардкодили stdout, а не передавали туда FILE *...)
причём судя по отчёту, ещё и тесты не все запускались, или с ними что-то странное произошло...

2022-01-08 14:47 UTC, leshiy1295 commented on CMakeLists.txt
> +# compile test for thread library
параллельная реализация отсутствует??

2022-01-08 14:47 UTC, leshiy1295 commented on CMakeLists.txt
> +#target_link_libraries(employ sort utils)
комментариев с нерабочим кодом быть не должно

2022-01-08 14:47 UTC, leshiy1295 commented on CMakeLists.txt
> +add_compile_options("--coverage")
этот флаг нужно добавлять только для тестов

2022-01-08 14:47 UTC, leshiy1295 commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror -Wpedantic -pthread")
-Wextra

2022-01-08 14:47 UTC, leshiy1295 commented on CMakeLists.txt
> +add_link_options( "-fsanitize=undefined")
санитайзеры нужно и другие добавлять, но по требованию

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +Employee *create_element(){
если она инициализирует структуру Employee, то почему она называется не create_employee или init_employee?

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    new_element->name = calloc(STR_SIZE, sizeof(char*));
по условию, программа должна работать с произвольным набором входных данных
сейчас Вы задаёте искусственное ограничение на размер полей

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    new_element->last_name = calloc(STR_SIZE, sizeof(char*));
почему sizeof(char*), а не sizeof(char)?

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +int position_initial(Position *element, const size_t *size){
init_position...
функция - это действие => глагол

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +int position_initial(Position *element, const size_t *size){
зачем передаётся size через указатель??

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +        return 2;
магические константы

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    element->youngest = (Employee**)calloc(*size, sizeof(Employee**));
опять же - неверная кратность указателя...
и в Си cast не нужен в этом контексте...

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    for(size_t i = 0; i < *n; ++i){
сейчас, если повторно вызвать эту функцию, будет ошибка
не забывайте занулять элементы после free

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    if(struc == NULL){
к чему эти сокращения?...

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +int free_position(Position *struc){
как, например, вот эта функция относится к sort_employee?

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +Position *get_worker_information (Employee **data, const size_t *N, const size_t *result_size, size_t *len ){
функция get обычно не изменяет данные
у Вас же она их сортирует...

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    qsort(data, *N, sizeof(Employee*), compare_position);
сейчас принцип сортировки захардкожен внутри и не очевиден пользователю

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    //подсчет количевтва должностей
хороший код должен документировать себя сам
вместо комментариев должны быть функции с понятными именами

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    size_t count_posit = 1;
непонятное название переменной

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    if (posit_array == NULL) return NULL;
сейчас вернётся NULL, что может быть воспринято, как "ошибка", но данные при этом поменялись (отсортировались)...

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +Position *get_worker_information (Employee **data, const size_t *N, const size_t *result_size, size_t *len ){
большими буквами - только глобальные константы
параметры - маленькими и с не однобуквенными именами

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +int fill_posit_array(Employee **data, Position *posit_array, const size_t *n){
то, что здесь идёт какое-то заполнение - и так ясно
но чтобы понять, какое именно - нужно смотреть код, что плохо
учитесь писать код так, чтобы всё было ясно из интерфейса

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +            count++;
где этот count используется??

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    const Employee *left  = *(const Employee **)elem_1;
входные аргументы могут быть NULL...

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    //сортируем по должности и возрасту
как это следует из кода?

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +int  employee_selection(Position *element, const size_t *result_size){
непонятно, какие функции являются интерфейсными и публичными, какие - приватными...
почему это всё в sort_employee..
почему нельзя было сделать отдельно функцию сортировки в отдельном модуле, модель - в другом, а компараторы - в третьем...

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +    // выбирает нужное количество сотрудников по каждой должности
нужное - это какое?

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +        position_initial(element, result_size);
это функция, а не процедура

2022-01-08 14:47 UTC, leshiy1295 commented on lib/sort_employee/sort_employee.c
> +            return 5;
непонятно, что это за магические константы...

2022-01-08 14:47 UTC, leshiy1295 commented on lib/utils/include/sort_employee.h
> +   size_t age;
тут образуется лакуна
эффективной упаковки, которая требовалась по заданию, тут нет

2022-01-08 14:47 UTC, leshiy1295 commented on lib/utils/include/sort_employee.h
> +int fill_posit_array(Employee **data, Position *posit_array, const size_t *n);
Я не верю, что все эти функции нужны в публичном интерфейсе...

2022-01-08 14:47 UTC, leshiy1295 commented on lib/utils/src/main.c
> +int main() {
функция main не должна содержать логику
вся логика должна быть вынесены в другие функции

2022-01-08 14:47 UTC, leshiy1295 commented on lib/utils/src/main.c
> +    size_t size = 0;  // количество сотрудников
positions_count
employees_count
и не нужны никакие комментарии...

2022-01-08 14:47 UTC, leshiy1295 commented on lib/utils/src/utils.c
> +Employee **read_data_from_file(const char *file_name, size_t *size){
непонятно, почему функция не протестирована

2022-01-08 14:47 UTC, leshiy1295 commented on lib/utils/src/utils.c
> +    fscanf(file, "%zu", size);
это не процедура, а функция - нужно проверять её результат

2022-01-08 14:47 UTC, leshiy1295 commented on lib/utils/src/utils.c
> +void print_employee(Employee *element){
функция нетестируема, т.к. сейчас в ней захардкожен stdout (можно тестировать, выводя в файл и проверяя содержимое файла ИЛИ перенаправляя с помощью freopen stdout, но это очень плохие решения)
стоило передавать сюда FILE *. Для main, если так нужно - достаточно было просто сделать локальную обёртку, которая просто вызывала бы эту функцию и передавала туда stdout (хоть в самом main)

2022-01-08 14:47 UTC, leshiy1295 commented on test/tests.cpp
> +        FAIL();
такого быть не должно

2022-01-08 14:47 UTC, leshiy1295 commented on test/tests.cpp
> +    if (element == nullptr) FAIL();
сейчас будет утечка position

2022-01-08 14:47 UTC, leshiy1295 commented on test/tests.cpp
> +TEST (test_cmp, test_cmp){
CamelCase

2022-01-08 14:47 UTC, leshiy1295 commented on test/tests.cpp
> +TEST (test_correct, test_correct_main){
непонятно, почему все эти тесты в одном месте

2022-01-08 14:47 UTC, leshiy1295 commented on test/tests.cpp
> +
стресс-тесты отсутствуют

2023-10-03 19:48 UTC, closed without merging